name: CI/CD for Salesforce Scratch Org

on:
  push:
    branches:
      - main   # Trigger the workflow for changes to the main branch or change as required
    paths-ignore:
      - 'assets/scratch-org-mappings.json'  

jobs:
  push-to-scratch-org:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install Salesforce CLI 
      - name: 'Install Salesforce CLI'
        run: |
          # Update the JSON file using jq
            BRANCH_NAME='main'
            DYNAMIC_ALIAS='DYNAMIC_ALIAS'
            NEW_USERNAME='test@test.com'
            jq --arg branch "$BRANCH_NAME" --arg alias "$DYNAMIC_ALIAS" --arg username "$NEW_USERNAME" \
            '.[$branch].alias = $alias | .[$branch].username = $username' \
             ./assets/scratch-org-mappings.json > tmp.json && mv tmp.json /assets/scratch-org-mappings.json

            # Display the updated JSON for debugging
            cat /assets/scratch-org-mappings.json
