name: CI/CD for Salesforce Scratch Org

on:
  push:
    branches:
      - main   # Trigger the workflow for changes to the main branch or change as required
    paths-ignore:
      - 'assets/scratch-org-mappings.json'  

jobs:
  push-to-scratch-org:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install Salesforce CLI 
      - name: 'Install Salesforce CLI' 
        run: |
          # Generate the password for the new scratch org
          PASSWORD='test'

          # Use a here-document to define the APEX_CODE
          APEX_CODE=$(cat <<EOF 
          String orgDetails = '$PASSWORD';
          Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
          mail.setToAddresses(new String[] {'shivprasad.patil@chargebee.com'});
          mail.setSubject('New scratch org has been created.');
          mail.setPlainTextBody(orgDetails+'.');
          Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});EOF)
