name: Create Scratch Org from Snapshot

on:
  workflow_dispatch:
    inputs:
      alias:
        description: 'Alias for the Scratch Org (e.g., 11thNov_CPQ)'
        required: true
        default: 'default-scratch-org'  # Default value if no alias is provided

jobs:
  create-scratch-org:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir ~/sfdx
          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          ~/sfdx/bin/sfdx version

          # Step 3: Checkout the source code (including snapshot-scratch-def.json)
      - name: 'Checkout code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history is available, especially for the snapshot
          
      # Step 2: Authenticate with Salesforce DevHub using JWT
      - name: 'Authenticate with DevHub'
        run: |
          sfdx force:auth:jwt:grant --client-id=${{ secrets.SALESFORCE_DEVHUB_CONSUMER_KEY }} \
                                    --jwt-key-file=./assets/server.key \
                                    --username=${{ secrets.SALESFORCE_DEVHUB_USERNAME }} \
                                    --set-default-dev-hub \
                                    --alias CBDEVHUB
      

      # Step 4: Create the Scratch Org from Snapshot using dynamic alias
      - name: 'Create Scratch Org from Snapshot'
        run: |
          echo "Creating Scratch Org with alias: ${{ github.event.inputs.alias }}"
          sf org create scratch --definition-file config/snapshot-scratch-def.json \
                                --alias ${{ github.event.inputs.alias }} \
                                --wait 10 \
                                --target-dev-hub sfcbdevhub1@chargebee.com.hub
          
      # Step 5: Output the created Scratch Org details
      - name: 'Display Scratch Org details'
        run: |
          echo "Fetching Scratch Org Info..."
          sf org display --targetusername ${{ github.event.inputs.alias }}
